name = "sat-game"
version = "0.1.0"
author = "Eric S. Rogstad"
defaultTargets = ["SATGame"]

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.20.0"

[[lean_lib]]
name = "SATGame"
